### ISSUE TITLE
Error: Invalid action: ' '

### ISSUE THREAD

**Issue by Xunius** [kevinw/pyflakes-vim#72]
I was setting up my gvim on Manjaro cinnamon which comes with a default python 3.5.1.
The pyflakes was installed via vundle, by the following line:

```
Plugin 'pyflakes.vim'
```

When starting a new .py file using vim, I got the following error.

```
Error detected while processing function <SNR>63_RunPyflakes:
line   53:
E927: Invalid action: ''
```

The vim version is 7.4

Please help

**Comment by evewind** [comment]
i got the same error.

**Comment by davvid** [comment]
Please test PR #74 and let me know if that fixes it for y'all too.

**Comment by Archloy** [comment]
Same error here, disable quickfix avoid error during opening .py file

**Comment by sorter** [comment]
I'm having this issue every time I use vim to open a pyton file

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 25 2016 23:46:25)
MacOS X (unix) version
Included patches: 1-102
Compiled by Homebrew
```

**Comment by davvid** [comment]
Use my fork and you won't have this problem.  That's the workaround.

The long-term solution, IIUC, is that pyflakes-vim is deprecated, and we should switch to syntastic instead.

In case it helps y'all, if you switch to syntastic you can configure your python checker to be "pyflakes" and get the same exact behavior as pyflakes-vim.  It also supports other checkers, e.g. "flake8".

**Comment by speq** [comment]
It indicates the error on the line:
                call setqflist(b:qf_list, '')
It should be
                call setqflist(b:qf_list, ' ')
to create new qflist.
There should be a space character inside the single quote.

**Comment by dhilst** [comment]
@speq is right!

Is any PR for that?
